name: nota
description: Nota package with the sub packages for server and app code
publish_to: none

version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  app:
    path: ./app
  server:
    path: ./server

dev_dependencies:
  flutter_lints: ^2.0.1  # linter rules
  test: ^1.16.0 # dart test package
  flutter_test: # flutter test package
    sdk: flutter
