name: nota
description: Nota package with the sub packages for server and app code
publish_to: none

version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.10.6

dependencies:
  app:
    path: ./app
  server:
    path: ./server

dev_dependencies:
  flutter_lints: ^2.0.1  # linter rules
  test: ^1.22.0 # dart test package
  flutter_test: # flutter test package
    sdk: flutter
