name: nota
description: Nota package with the sub packages for server and app code
publish_to: none

version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  app:
    path: ./app
  server:
    path: ./server

