name: app
description: The App Part of Nota
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared: # shared code
    path: ../shared

  cupertino_icons: ^1.0.2 # default icons
  get_it: ^7.2.0 # service locator
  hive: ^2.2.3 # nosql database
  hive_flutter: ^1.1.0 # flutter extension 


dev_dependencies:
  flutter_test: # flutter test package
    sdk: flutter

  flutter_lints: ^2.0.1 # linter rules


flutter:

  uses-material-design: true