name: app
description: The App Part of Nota
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ^3.7.5

dependencies:
  flutter:
    sdk: flutter
  shared: # shared code
    path: ../shared

  cupertino_icons: ^1.0.2 # default icons
  meta: ^1.8.0 # annotations like immutable
  get_it: ^7.2.0 # service locator
  flutter_bloc: ^8.1.2 # BLoC state management
  tuple: ^2.0.0 # tuples
  path_provider: ^2.0.12 # application directory path
  hive: ^2.2.3 # nosql database
  hive_flutter: ^1.1.0 # flutter extension for hive
  flutter_secure_storage: ^8.0.0 # secure storage for keys in keychain, or keystore. NEEDS LINUX SPECIFIC SETUP!
  cryptography: 2.1.1 # basic cryptographic functions (like aes encryption)
  cryptography_flutter: ^2.0.2 # better flutter performance for base package
  dargon2_flutter: ^3.2.0 # argon2 implementation. MIGHT NEED IOS specific setup!
  flutter_svg: ^2.0.2 # svg images
  flutter_native_splash: ^2.2.19 # splash screen. NEEDS IOS SPECIFIC SETUP!
  flutter_launcher_icons: ^0.12.0 # app launcher icon
  flutter_keyboard_visibility: ^5.4.0 # keyboard visibility callback
  localization: 2.1.0 # localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  test: ^1.16.0 # dart test package
  flutter_test: # flutter test package
    sdk: flutter

  flutter_lints: ^2.0.1 # linter rules

  server: # server project is needed only for testing
    path: ../server

flutter:

  uses-material-design: true

  assets: # the asset folder for images and translation files
    - assets/

flutter_icons: # create new launcher icons with flutter pub run flutter_launcher_icons
  image_path: "assets/app_icon_light.png" # could also use the dark theme icon
  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: true
  remove_alpha_ios: true # alpha is not allowed on apple app store
  web:
    generate: true
    image_path: "assets/app_icon_light.png" # same as above
  windows:
    generate: true
    image_path: "assets/app_icon_light.png" # same as above
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon_light.png" # same as above