name: app
description: The App Part of Nota
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared: # shared code
    path: ../shared

  cupertino_icons: ^1.0.2 # default icons
  get_it: ^7.2.0 # service locator
  hive: ^2.2.3 # nosql database
  hive_flutter: ^1.1.0 # flutter extension for hive
  flutter_secure_storage: ^8.0.0 # secure storage for keys in keychain, or keystore
  cryptography: ^2.0.5 # basic cryptographic functions (like aes encryption)
  cryptography_flutter: ^2.0.2 # better flutter performance for base package
  path_provider: ^2.0.12 # application directory path

dev_dependencies:
  test: ^1.16.0 # dart test package
  flutter_test: # flutter test package
    sdk: flutter

  flutter_lints: ^2.0.1 # linter rules

  server: # server project is needed only for testing
    path: ../server

flutter:

  uses-material-design: true