name: server
description: The Server part of Nota
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  shared: # shared code
    path: ../shared

  get_it: ^7.2.0 # service locator
  hive: ^2.2.3 # nosql database
  args: ^2.4.0 # command line argument parsing
  synchronized: ^3.0.1 # locks for concurrent access
  intl: ^0.17.0 # internationalization

dev_dependencies:
  flutter_lints: ^2.0.1 # linter rules
  test: ^1.23.1 # dart test package