name: server
description: The Server part of Nota
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  shared: # shared code
    path: ../shared

  get_it: ^7.2.0 # service locator
  hive: ^2.2.3 # nosql database
  args: 2.3.2 # command line argument parsing
  synchronized: 3.0.1 # locks for concurrent access

dev_dependencies:
  flutter_lints: ^2.0.1 # linter rules
  test: ^1.16.0 # dart test package