name: shared
description: Shared Component with Code for both Server and App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  equatable: ^2.0.5 # comparing objects
  http_parser: ^4.0.2 # parsing content type and media type
  http: ^0.13.5 # http client

dev_dependencies:
  flutter_lints: ^2.0.1  # linter rules
  test: ^1.16.0 # dart test package