/// This file is automatically generated from the "Create New Keys" run configuration.
class SensitiveData {
  /// Used when creating the user key from the password (which will only be stored inside the app).
  ///
  /// Should be a long random character sequence. Is Base64 encoded!
  static const String userKeySalt = "fRDlRsn9dSMYj2vDXmPxXZA7urWgaXFkVp6tt7VygZE=";
}
